### ISSUE TITLE
Code:-11 primary error: 3 certificate: Issued to

### ISSUE THREAD

**Issue by BoskiOskii** [AzureAD/azure-activedirectory-library-for-android#1137]
<ul>
  <li>Displaying WebView with ADFS login screen</li>
  <li>WebView disappearing after receiving error</li>
  <li>com.microsoft.aad.adal.AuthenticationException: Code:-11 primary error: 3 certificate: Issued to: CN=* Issued by: *</li>
</ul>

Hello, I'm getting this error on Android 7.1: com.microsoft.aad.adal.AuthenticationException: Code:-11 primary error: 3 certificate: Issued to: CN=* Issued by: *

I tried to update Chrome, disable chrome and update WebView alone. Nothing works so far. This code is working from 2 years on android 4.4+. My cert is self signed.

**Comment by iambmelt** [comment]
Hi @BoskiOskii - Due to the inherent security risks associated with self-signed certs, ADAL does not support the use of SSL certificates whose issuance or revocation cannot be validated against a known authority.

For more information about the risks of associated self-signed certs in this context, please see [Sec:StackExchange](https://security.stackexchange.com/a/8112).

There are no plans to add support for self-signed certificates at this time.

**Comment by BoskiOskii** [comment]
@iambmelt Thank you for your answer! :)
