### ISSUE TITLE
Token from ADFS with extra claims

### ISSUE THREAD

**Issue by fatihergin** [AzureAD/azure-activedirectory-library-for-android#1224]
I'm using this library to authenticate an Android user with ADFS. 
In regular way, when we request a token from ADFS, it adds extra claims to token (LDAP attributes as relying trust identifier which we defined on ADFS side) before returns the token.

We created a native application on Azure Active Directory portal and configured it to acquire token from ADFS.
We used the "Windows Azure Active Directory" api as the resource (RESOURCE_ID = "00000002-0000-0000-c000-000000000000").
The token returns successfully when we try to login. But we need to add extra claims to Id token in ADFS side using LDAP attributes.

How can we configure the token for this native client? Is it a configuration issue or am I missing the big picture?

**Comment by danieldobalian** [comment]
Can you clarify what you're referring to as a regular way here:

`In a regular way, when we request a token from ADFS, [...]`

**Comment by fatihergin** [comment]
Hi @danieldobalian,
We define a new relying party trust and add its identifier on ADFS. After that, adding the custom LDAP attributes to this relying party trust is enough to get the token with added LDAP attributes. 
This is the first Android-ADFS project and we don't know how to add expected identifier on ADFS to get token with custom attributes.

**Comment by iambmelt** [comment]
Closing, as this issue pertains more closely to AAD management and configuration, rather than this Android library specifically.

The best place to get help from our teams on this issue is [Stack Overflow](https://stackoverflow.com/), where our PMs, developers, support staff, and enthusiastic customers spend time answering questions. There's already a great deal of good information on Stack Overflow, so be sure to do some searching before asking your own question. If you do need to post a question, please follow these guidelines:

- Use the appropriate tag for your issue. Some tags we monitor include `adal`, `azure-active-directory`, `microsoft-account`, and `microsoft-graph`.
- When you write your question, do so in a way that will be useful for other developers in the future. Use a good title, provide enough detail to fully understand the problem, etc. Stack Overflow provides nice guidance on [How do I ask a good question](https://stackoverflow.com/help/how-to-ask) and [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).
- In particular, most questions will require you to share examples of the code you've written, as well as exception messages, error codes, stack traces, and the like. If you are not including code in your post, you should be really sure it's not necessary.
