### ISSUE TITLE
failure in Discovery#validateAuthority breaks getting tokens from local cache until restart!

### ISSUE THREAD

**Issue by demoritas** [AzureAD/azure-activedirectory-library-for-android#1355]
Tokens are store in the DefaultTokenCacheStore using the information from the Discovery result. 
When started without connection or when the Discovery endpoint is unreachable AquireTokenRequest#248 adds the current authority host to AuthorityValidationMetadataCache.

This leads to requests to the local cache retuning no token in some cases.

If the app tries to get a token at a later point of time, being online the Discovery is not re-run because of the check in  AquireTokenRequest#243. This effectively prevents getting tokens from cache for the lifetime of the VM.

in our case:
authority: https://login.microsoftonline.com/common
discovery returns: https://login.windows.net/common

in the token cache:
no token for: https://login.microsoftonline.com/common$https://outlook.office.com/$XXXXX
existing token for: https://login.windows.net/common$https://outlook.office.com$XXXXX

Please ensure the following information is provided when logging a new issue:

* Expected behavior
getting tokens from cache in offline mode works if token is in cache
getting tokens after switching to online mode works

* Actual behavior
getting tokens from cache while being offline returns AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED and breaks the getting tokens from cache for the lifetime of the VM
 
* Specifications like the version of the library, operating system etc.
reproduces for 1.15 and 1.16
validateAuthority is set to false

**Comment by danieldobalian** [comment]
Followed up directly. There are some circumstances you may need to disable validateAuthority, such as B2C in MSAL and in certain ADFS cases.

**Comment by demoritas** [comment]
May I ask why this is closed? validateAuthority=true  only hides the issue, it is still clearly a bug which potentially affects all apps which use validateAuthority=false. The bug is not resolveable unless you terminate (just open/close is not sufficient) the app in question.

**Comment by iambmelt** [comment]
To contribute some root-cause to this thread: [this is the check](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L243) which is preventing discovery metadata from being loaded -- the `AuthorityValidationMetadataCache` is not updated because [in the event of failure to load] the [unvalidated authority is passed to the metadata cache and flagged as `false == isValidated`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AuthorityValidationMetadataCache.java#L82-L85).

The library never attempts to 'recover' from this state

**Comment by iambmelt** [comment]
Synced offline, this looks to be a relative corner case with few incidences reported. I am going to close this issue as 'wontfix' assuming a low-pri, please post-back if this issue continues to be a problem requiring a fix and we will prioritize accordingly.
