### ISSUE TITLE
Configuring ADAL for MAM SDK

### ISSUE THREAD

**Issue by pblue92** [AzureAD/azure-activedirectory-library-for-android#1486]
I want to integrate intune in my Android Application. Currently, I use the IdentityClient SDK to integrate the Outlook calendar in my application. I just want to know do I have to configure ADAL in this scenario if I have to use Conditional Access in my application?

**Comment by iambmelt** [comment]
Hi @pblue92 -- I've taken the liberty of retitling the question to better reflect the content. Feel free to review and rename if I've misunderstood the question.

Check out the following ADAL Configuration guidance:
https://docs.microsoft.com/en-gb/intune/developer/app-sdk-android#configure-azure-active-directory-authentication-library-adal

The metadata items in the ADAL configuration instructions you’ve linked are used by the MAM SDK for authentication and conditional launch scenarios. Even though you’re using MSAL, the Intune SDK (MAM) uses ADAL under the hood so the referenced metadata items still to be provided from the ADAL instructions. The authority, client id, and redirect URI values should be the same as you’ve configured for your app’s usage of MSAL. The skip-broker value should reflect whether your app uses the broker or not.

Since we have an offline thread going via email I am going to close this issue. Feel free to reopen if you would like to continue the conversation here.
