### ISSUE TITLE
ADAL 1.16.+ domain hint with MS Authenticator not woking

### ISSUE THREAD

**Issue by ChristianGiuseppe** [AzureAD/azure-activedirectory-library-for-android#1489]
When I login on my application with MS Authenticator the value of the extraQueryParameters parameter is ignored

this is my code:

-  mAuthContext.acquireToken(activity, resource, clientId, mAuthContext.getRedirectUriForBroker(),  PromptBehavior.Auto, "domain_hint=example.com", getAuthInteractiveCallback());

**Comment by kreedula** [comment]
Hi @ChristianGiuseppe : Thank you for reporting, Few questions below

- Did this ever work with any version of Authenticator app ? 
- Can you post the version of the Authenticator app you're using?
- When you mean ignore , how are determining that it is ignored? if you're looking at network traces can you let us only if it's ignored while sending to Authorize endpoint(`oauth2/authorize`) or Token Endpoint(`oauth2/token`) or both?

By design, in Authenticator app(Broker), we allow all the extra query params passed by the client to the Authorize endpoint but we only allow specific query params to the Token endpoint , domain_hint isn't one of them.

**Comment by ChristianGiuseppe** [comment]
Hi @kreedula,
I tried with the latest version of the Authenticator (version 6.2001.0140)
I realized that it is ignored because when the MS Authenticator application is not installed, the parameter is read correctly because the webview that shows the domain is not displayed.
Could you tell me what are the specific parameters that can be sent to the token endpoint?
