### ISSUE TITLE
Acquiring tokens with user credentials?

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-android#325]
I was wondering if there was an equivalent of Microsoft.IdentityModel.Clients.ActiveDirectory's method:

AcquireToken(string resource, string clientId, UserCredential userCredential);

Which allows me to pass in the user credentials to acquire a token versus having to enter in a username and password into the login prompt. Currently, our issue with using this library is that our organization's login page has a popup window for the windows credentials which the android webview can't seem to handle. It seems like no matter what we do, we never get the forms authentication option, we always get the browser popup for authentication. If we could, in android, pass the username and password as a user credential as we can in the C# Microsoft.IdentityModel.Clients.ActiveDirectory library, it would solve the issue completely that we're having with that popup not rendering properly.

**Comment by duongthaiha** [comment]
Jose
We are having similar issue with the web view and we want to bypass it. Is that possible to give us some idea on what did you do to avoid web view please? Thank you very much

**Comment by josephyanks** [comment]
So when I said that this was fixed, I was mistaken. Are you by chance getting an 'SSL_HANDSHAKE' error? That was the root issue that was actually causing the webview to close, not the popup (red herring there). After speaking to someone who works on this library, it seems like the root cause might be the fact that there is the redirect when you use the company identifier. During that redirect, you hit an endpoint that has a self-signed certificate (common with ADFS setup) which android's webview is unable to handle and the authentication fails. I have yet to get this library to work with our application and ADFS setup, since I do not have control over the certificates that the company uses on their login portal.

This is a suggestion that I got to try to troubleshoot the issue with the SSL_HANDSHAKE: Try to add the ADFS certificate to your trusted sources on the box running the web API and the device consuming it

Let me know if that helps at all?

**Comment by duongthaiha** [comment]
Thank you very much. Currently we are trying to have a native java application which then authenticate user with username and password. We will investigate your suggestion and see if we can do something about it. Its our case, our application so we do have access to the certificate

**Comment by josephyanks** [comment]
Just an FYI, our IT department fixed the issue with the SSL cert and now the ADAL library works for us. It's probably worthwhile to look into getting the proper certificate - that should resolve your issues
