### ISSUE TITLE
Handle common endpoint so that reprompt is avoided when tenant specific authority is used after.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#436]
It appears that once a token is acquired via the common endpoint there is no way to re-use that token with the actual tenant authority from which the token is issued.  We need to have a way of correlating common and tenant specific acquired tokens in the cache in a way that avoid prompting when it is not truly necessary.

**Comment by heidijinxujia** [comment]
Need to have a look on the .net implementation as a reference.

**Comment by heidijinxujia** [comment]
Use the user's home tenant instead of the common tenant in the key of SharePreference. (Reference on the cache implementation of iOS and .NET) As a result, only the tenant specific acquired tokens are stored in the cache and get re-used. While the common tenant acquired tokens will be prompted.

**Comment by heidijinxujia** [comment]
To handle the multi tenant situation in the future and maintain the current version functionality as well, my proposed solution for this issue is to store both the common tenant and specific tenant as separate items in the SharedPreference. The current problem is that we do not have the attribute to keep the returned Authority in the AuthenticationResult class. We could not get the specific tenant address from the AuthenticationResult unless when add an attribute to store it from the bundle returned from the server.

**Comment by heidijinxujia** [comment]
@RandalliLama

**Comment by nazukj** [comment]
This issue will be taken as a feature request for V2. Thanks for the feedback!
