### ISSUE TITLE
Remove @style/AppTheme from manifest

### ISSUE THREAD

**Issue by madhusudankapoor** [AzureAD/azure-activedirectory-library-for-android#440]
AndroidManifest.xml:16:9-42
    is also present at [:adal-1.1.3:] AndroidManifest.xml:13:9-40 value=(@style/AppTheme)

**Comment by weijjia** [comment]
Why do you want this to be removed?

**Comment by madhusudankapoor** [comment]
In the AndroidManifest.xml of the lib currently you have android:theme="@style/AppTheme" ; 

it should not present in lib project. so see if you can remove android:theme="@style/AppTheme" from below tag

<application
        android:allowBackup="true"
        android:theme="@style/AppTheme" >
        <activity android:name="com.microsoft.aad.adal.AuthenticationActivity" >
        </activity>
    </application>


OR

If you like to keep, then add tools:replace="android:theme"  in  <application ... > and xmlns:tools="http://schemas.android.com/tools" in manifest

<manifest xmlns:tools="http://schemas.android.com/tools" ...

**Comment by madhusudankapoor** [comment]
Any update?

**Comment by madhusudankapoor** [comment]
Any update?

**Comment by weijjia** [comment]
Done. Already released in the latest version.

**Comment by max-bb** [comment]
This has reappeared in 1.15.0; the com.microsoft.identity library is now defining an appTheme when it should not.

**Comment by iambmelt** [comment]
@max-bb I suspect that this is due to ADAL adding a dependency on [`common`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android) which, until recently, did erroneously include an [`appTheme`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/301).

Related issues can be found below:
- https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/440
- https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/301

This should be fixed in an upcoming release (`>1.16.1`) but I don't have a specific date for when these changes will be available yet.

**Comment by iambmelt** [comment]
Reopening.

**Comment by bannus** [comment]
ADAL's `values-v14/styles.xml` can override my app's `values/styles.xml` if I use the name `AppTheme` or `AppBaseTheme`.

The `styles.xml` files in ADAL are unused AFAIK and have been present since the [initial commit](https://github.com/AzureAD/azure-activedirectory-library-for-android/commit/3014b2b56aefd6c8381225e94957f643fe8321ee#diff-f3b0883918b76f5247f81e2d2f350a3d). Seems like they should just be removed.

**Comment by iambmelt** [comment]
Cannot change this due to backcompat breaks - closing
