### ISSUE TITLE
ADAL Library is not storing multi resource refresh token

### ISSUE THREAD

**Issue by vineetsetia** [AzureAD/azure-activedirectory-library-for-android#543]
Hey,
I am using ADAL SDK 1.1.10 and when I am calling adal library multiple times, it is getting me new access token everytime. Can you please look into this ? Please let me know if you need logs for this.

Thanks,
Vineet

**Comment by weijjia** [comment]
I don't quite understand your issue. If it's ADAL not storing multi-resource refresh token, ADAL store the multi-resource based on the return from server. what is the authority? multi-resource refresh token is the concept restricted to AAD, if you talk to ADFS directly, they don't return us the multi-resource refresh token. If your issue is, when you call adal multiple times, you get new access token everytime. You need to send us the logs. Usually, access token is only valid for 1 hour.

**Comment by addev-ashish** [comment]
@vineetsetia this issue has been open for a while, kindly let us know if you are still hitting this issue.
