### ISSUE TITLE
If useBroker set to TRUE and one of broker app installed returns error that app needs Permissions

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#730]
1.2 has tried to sign in using local cache and only if it fails returned error, while 1.10 rejects request even without trying to obtain token w/o broker.

**Comment by weijjia** [comment]
This is by design. If app opts in to use broker and broke is installed on device, we send back the exception indicating that permission is missing. The intention behind this is to explicitly tell app that we need permission to continue the auth request and app can request runtime permission when receiving the specific error code.
