### ISSUE TITLE
Adal is not retry query for token when back from  company portal login

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#821]
Prerequisite:
An account  with azure conditional access enabled, which requires compliant devices in order to login (Means user need to install company portal and login to it first to be able to use the app).
App is in broker mode
Steps:
1. login adal with the test account
2. adal oauth page shows up and input the test accounts and password
3. adal jump to a page says 'your device must be managed by microsoft before you can use this application' with Enroll button
4.click the enroll button to download the company portal
5.login the company portal and wait it finished the enrollment.
6.Open App from background and adal context returns, and OnActivityResult is triggered with AuthenticationConstants.UIResponse.BROWSER_CODE_CANCEL.
The AuthenticationCallback onError  triggered with ApplicationCancelError.

Expected: adal should retry when app back to foreground and return with success.

Feel free to email me for get test accounts or video/screenshot/log.

**Comment by weijjia** [comment]
This is by design. Whenever "enroll" is clicked, we expect user interaction here. User has to install company portal and sign-in to company portal to finish the MDM flow. The best way adal can do here is to cancel the current flow, once user finished the whole device enrollment thru the company portal, re-start the token acquisition flow.
