### ISSUE TITLE
Possible incorrect error code returned 

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#833]
Here are a couple logs got from users while refresh token in sequence:
1.	
Class:HttpWebRequest message:2017-05-09 03:54:13-619ad5c8-9d2f-4b62-8689-1f8608f44ee8-IOException:https://login.microsoftonline.com/common/oauth2/token ver:1.12.0 additionalMessage: level:Error errorCode:SERVER_ERROR
2Class:HttpWebRequest message:2017-05-09 03:54:14-619ad5c8-9d2f-4b62-8689-1f8608f44ee8-IOException:https://login.microsoftonline.com/common/oauth2/token ver:1.12.0 additionalMessage: level:Error errorCode:SERVER_ERROR
3 Class:HttpWebRequest message:2017-05-09 03:54:14-619ad5c8-9d2f-4b62-8689-1f8608f44ee8-IOException:https://login.microsoftonline.com/common/oauth2/token ver:1.12.0 additionalMessage: level:Error errorCode:SERVER_ERROR
4.Class:AcquireTokenRequest message:2017-05-09 03:54:16-619ad5c8-9d2f-4b62-8689-1f8608f44ee8-Prompt is not allowed and failed to get token: ver:1.12.0 additionalMessage:Request authority:https://login.microsoftonline.com/common resource:https://www.yammer.com/ clientid:d3590ed6-52b3-4102-aeff-aad2292ab01c No result returned from acquireTokenSilent level:Error errorCode:AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED

For the last AcquireTokenRequest log, why the errorCode is not SERVER_ERROR?

We are on 1.12 of adal

**Comment by heidijinxujia** [comment]
Hi @hjymandroid thank you for filing this issue. Could you send me the full log? According to the logs you attached here, it seems you are doing the acquireToken call and a silent auth is tried first. And errorCode:AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED is thrown because there is no access token returned from the silent call. Do you know which exception is sent to the callback (it should shown in the full adal logs)? It is expected that an AuthenticationException with ADALError.AUTH_FAILED_NO_TOKEN should be thrown to the callback. It would be very helpful for the investigation if you could share the full verbose level adal logs with us. Thanks.

**Comment by hjymandroid** [comment]
See whether you can access the following sumologic link:
https://service.sumologic.com/ui/#section/search/LINozN770jF8ALe51Eeq8TE8skXlLaZ27VI4fm4R

**Comment by heidijinxujia** [comment]
I checked Kusto with the attached correlationID 619ad5c8-9d2f-4b62-8689-1f8608f44ee8. And it shows the server returned the ServiceException which said "The refresh token has expired due to inactivity." And because you were making an acquireTokenSilentSync call (*where the prompt is not allowed*) with an expired refresh token (*this is why the refresh token failed*), it is by design that errorCode:AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED is thrown. And when getting this errorCode, the developer could make an acquireToken interactive call to continue the auth.

**Comment by heidijinxujia** [comment]
Thank you again for filing this issue and please feel free to open an issue if you have any further questions.
